apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageprocessingjobs.darwinist.io
spec:
  group: darwinist.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - s3_input_location
                - model_name
                - s3_output_location
              properties:
                s3_input_location:
                  type: string
                model_name:
                  type: string
                s3_output_location:
                  type: string
  scope: Namespaced
  names:
    plural: imageprocessingjobs
    singular: imageprocessingjob
    kind: ImageProcessingJob
    shortNames:
      - ipj