apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
  - apiGroups: ["darwinist.io"]
    resources: ["imageprocessingjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch", "batch/v1", "extensions/v1beta1"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: darwinist
roleRef:
  kind: ClusterRole
  name: operator-cluster-role
  apiGroup: rbac.authorization.k8s.io