
name: API Server CI/CD

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: api_server
        env:
          # IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/your_api_server_image
          IMAGE_NAME: darwinist/operator_api_server
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ls
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f api_server.Dockerfile ./api_server
          docker push $IMAGE_NAME:$IMAGE_TAG
